### ISSUE TITLE
import error when running the Recommender notebook

### ISSUE THREAD

**Issue by KVSSetty** [aayushmnit/cookbook#2]
Hello, I was just trying your notebook after reading your wonderful blog , I got the following error and unable to debug ,any  help please.

steps taken:
1.cloned the repo
2.opened the Recommender notebook
3.cleared the previous outputs in the note book.
4.executed the first cell , that is the importing cell and got the following error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-4d0d7cd137cc> in <module>()
      3 sys.path.append(os.path.abspath("../"))
      4 from recsys import *
----> 5 from generic_preprocessing import *
      6 from IPython.display import HTML

ModuleNotFoundError: No module named 'generic_preprocessing'

I am on windows 10

**Comment by aayushmnit** [comment]
Please have notebooks and cookbook codes(recsys.py and generic_preprocessing.py) in one directory. I created a notebook section to illustrate how cookbooks can be used. It's not supposed to be run as a repository directly.
