### ISSUE TITLE
How work with big dataset?

### ISSUE THREAD

**Issue by niksib** [aayushmnit/cookbook#3]
Hello.
I try to work with the ml-latest dataset and got error "Memory error".
How to work with a large dataset, I should split this data, but how I can recommend something based on half of the data?

**Comment by aayushmnit** [comment]
Hello!

I think this question is not relevant to this GitHub repository as the repo contains code to do things quickly with the moderate sized dataset. Still, there are various ways to do that -
- Try on optimizing your import in pandas, the default for numeric is float64, you can reduce it to float8,16.32 based on datatype (Check this kernel - https://www.kaggle.com/shrutimechlearn/large-data-loading-trick-with-ms-malware-data)
- Try algorithms which work on batch datasets, active learning or stochastic gradient descent method
- Try running your code on a bigger machine which can accommodate data in RAM
- Try distributed computing on Spark and use Spark MLlib

Hope these help!
